name: Trigger auto deployment for vlsmapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vlsmapi-AutoDeployTrigger-3ab0f7da-069e-4a4f-9f73-09c0b7ea9402.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VLSMAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VLSMAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VLSMAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.VLSMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VLSMAPI_REGISTRY_PASSWORD }}
          containerAppName: vlsmapi
          resourceGroup: vlsm
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


